name: Update Abilities DLL

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-dll:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Abilities DLL
        run: |
          RELEASE_NAME=$(curl -s "https://api.github.com/repos/Soof4/Abilities/releases/latest" | grep -oP '"tag_name": "\K(.*)(?=")')
          wget -q "https://github.com/Soof4/Abilities/releases/download/$RELEASE_NAME/Abilities.dll"
        shell: bash

      - name: Push DLL to Dependencies
        run: |
          git pull origin main
          cp Abilities.dll Dependencies/
          git config user.name "Github Actions"
          git config user.email "emr3.cbc@gmail.com"
          git add Dependencies/Abilities.dll
          git commit -m "Update Abilities DLL"
          git push origin HEAD:main -f
        shell: bash
